ecommerceproject/cart/urls.py
from . import views
from django.urls import path
app_name='cart'
urlpatterns = [
    path('add/<int:product_id>/',views.add_cart,name="add_cart"),
    path('', views.cart_detail, name='cart_detail'),
    path('cart_remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/', views.full_remove, name='full_remove'),

]

ecommerceproject/credential/urls.py
from django.contrib import admin
from . import views
from django.urls import path, include

app_name='credential'
urlpatterns = [
    path('/register',views.register,name='register'),
    path('/login',views.login,name='login'),
    path('/logout',views.logout,name='logout'),
]

ecommerceproject/ecommerceproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('/search',include('search_app.urls')),
    path('/cart',include('cart.urls')),
    path('/credential', include('credential.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerceproject/search_app/urls.py
from django.contrib import admin
from . import views
from django.urls import path
app_name='search_app'
urlpatterns = [

    path('', views.searchResult, name='searchResult'),

]

ecommerceproject/shop/urls.py
from django.contrib import admin
from . import views
from django.urls import path, include
app_name='shop'
urlpatterns = [
    path('',views.allProdCat,name='allProdCat'),
    path('<slug:c_slug>/', views.allProdCat, name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/',views.proDetails,name='prodcatdetail'),

]

ecommerceproject/cart/models.py
from django.contrib.auth.models import User
from django.db import models
from shop.models import Product


# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)

    class Meta:
        db_table='cart'
        ordering=['date_added']
    def __str__(self):
        return '{}'.format(self.cart_id)

class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)

    class Meta:
        db_table='CartItem'

    def sub_total(self):
        return self.product.price*self.quantity

    def __str__(self):
        return '{}'.format(self.product)
class CartUserMapping(models.Model):
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)

ecommerceproject/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.
from .models import Cart,CartItem,CartUserMapping
from shop.models import Product

from django.core.exceptions import ObjectDoesNotExist


def _cart_id(request):
    if request.user.is_authenticated:
        user_id=request.user.id
        if CartUserMapping.objects.filter(user=user_id):
            cart=CartUserMapping.objects.get(user=user_id).cart
        else:
            cart = request.session.session_key
            #CartUserMapping.objects.create(cart=cart,user=request.user)
            if not cart:
                cart = request.session.create()
            print(cart)
            #CartUserMapping.objects.create(cart=cart,user=request.user_id)
        #try:
         #   cartuser=CartUserMapping.objects.get(user=user_id)
         #   cart = cartuser.cart


       # except ObjectDoesNotExist:
           # cart = request.session.session_key
            #print(cart)
            #if cart:
             #   if not CartUserMapping.objects.filter(cart=cart, user=request.user).exists():
            #        CartUserMapping.objects.create(cart=cart, user=request.user)
            #if cart:
                #cartuser=CartUserMapping.objects.create(cart=cart,user=user_id)
            #else:
           # if not cart:
           #     cart = request.session.create()
                #cartuser = CartUserMapping.objects.create(cart=cart, user=user_id)
    else:
        cart=request.session.session_key
        if not cart:
            cart=request.session.create()
    return cart
def add_cart(request,product_id):
    product=Product.objects.get(id=product_id)

    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        print("cart exist")
        print(cart.id)
    except Cart.DoesNotExist:
        cart=Cart.objects.create(cart_id=_cart_id(request))
        cart.save()
        print("does not exist")
        if request.user.is_authenticated:
            user= request.user
            if not CartUserMapping.objects.filter(cart=cart,user=user).exists():
                CartUserMapping.objects.create(cart=cart,user=user)
    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity<cart_item.product.stock:
            cart_item.quantity+=1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')
def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total+=(cart_item.product.price*cart_item.quantity)
            counter+=cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))
def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity>1:
        cart_item.quantity-=1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')
def full_remove(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

ecommerceproject/templates/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{%block metadescription%}{%endblock%}">

    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet" >
     <link href="{% static 'css/custom.css'%}" rel="stylesheet" >
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;1,100&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>{%block title%}{%endblock%}</title>
</head>
<body>
<div class="container-fluid">
{%include 'header.html'%}
{%include 'nav.html'%}
{%block content%}
{%endblock%}
</div>
{%include 'footer.html'%}
<script src="{% static 'js/bootstrap.bundle.min.js'%}" ></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
</body>
</html>

ecommerceproject/templates/cart.html
{%extends 'base.html'%}
{% load static%}
{%block metadescription %}
This is the cart page .Proceed to review your items and place the order
{%endblock%}
{%block title%}
Cart
{%endblock%}
{%block content%}
{%if not cart_items%}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">Your shopping cart is Empty</h1>
        <p class="text-center">Please Click <a href="{%url 'shop:allProdCat' %}">here</a>to continue shopping</p>
    </div>
</div>
{%else%}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">Your shopping cart</h1>
        <br>
    </div>
</div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th colspan="5">Yor Items</th>
            </tr>
            </thead>
            <tbody>
            {%for cart_item in cart_items%}
            <tr>
                <td>
                    <a href="cart_item.product.get_absolute_url"><img width="100px"height="100px" src="{{cart_item.product.image.url}}" alt="" class="float_left rounded custom_image"></a>
                </td>
                <td class="text-left">
                    {{cart_item.product.name}}
                    <br>
                    SKU:{{cart_item.product.id}}
                    <br>
                    Price:{{cart_item.product.price}}
                    <br>
                    Qty:{{cart_item.quantity}}X{{cart_item.product.price}}
                </td>
                <td>
                    {{cart_item.sub_total}}
                </td>
                {%if cart_item.quantity < cart_item.product.stock%}
                <td>
                    <a href="{%url 'cart:add_cart' cart_item.product.id%}"class="custom_a"><li  class="fa fa-plus custom_icon"></li></a>
                    &nbsp;<a href="{%url 'cart:cart_remove' cart_item.product.id%}" class="custom_a"><li  class="fa fa-minus custom_icon"></li></a>
                     &nbsp;<a href="{%url 'cart:full_remove' cart_item.product.id%}" class="custom_a"><li  class="fa fa-trash custom_icon"></li></a>
                </td>
                {%else%}
                <td>
                    <a href="{%url 'cart:cart_remove' cart_item.product.id%}"class="custom_a"><li  class="fa fa-minus custom_icon"></li></a>
                     &nbsp<a href="{%url 'cart:full_remove' cart_item.product.id%}"class="custom_a"><li  class="fa fa-trash custom_icon"></li></a>
                </td>
                {%endif%}
            </tr>
            {%endfor%}
            </tbody>

        </table>

    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th colspan="5">Checkout</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    Please review your shopping cart before poroceeding the order payment
                </td>
            </tr>
            <tr>
                <td class="text-left">
                    Your Total is:<strong>{{total}}</strong>

                </td>
            </tr>
            </tbody>
        </table>
        <div class="mx-auto"><br><br>
            <a href="{% url 'shop:allProdCat'%}" class="btn btn-secondary btn-block my_custom_btn">Continue Shopping</a>

        </div>
    </div>
</div>
{%endif%}


{%endblock%}

ecommerceproject/templates/category.html
{%extends 'base.html'%}
{% load static%}
{%block metadescription %}
    {% if category %}
        {{category.description|truncatewords:155}}
    {%else%}
        Welcome to ithal ,where you can buy different items
    {%endif%}
{%endblock%}
{%block title%}
{% if category %}
        {{category.name}}
    {%else%}
        see our new collection-itahl
    {%endif%}
{%endblock%}
{%block content%}
{%if category%}
<div>
    <div>
        <p><a href="{%url 'shop:allProdCat' %}">Our Product Collection</a></p>
    </div>
</div>
{%endif%}
<div class="row my_row_class ">
    <div class="mx_auto container">
        {%if category%}
            <div>
                <img class="my_img my_img_padding"src="{{category.image.url}}" alt="{{category.name}}">
            </div>
<div>
 <h1 class="text-center my_title">{{category.name}}</h1>
  <p class="text-justify">{{category.description}}</p>
</div>
    </div>
{%else%}
    <div>
        <img src="{%static 'img/banner.png'%}"alt="Our Products"width="100%" height="350px">

    </div><br>

    <div>
        <h1>Our product Collection</h1>
        <p></p>
    </div>
    </div>

{%endif%}
<div class="container">
    <div class="row">
    {%for product in products.object_list%}
        <div class="col-md-4 col-9 col-sm-12 col-lg-4 my_bottom_margin">
    <div class="card text-center" style="min-width:18rem;height:25rem;">
        <a href="{{product.get_url}}"><img class="product_img product_img_padding"src="{{product.image.url}}" class="card-img-top" alt="..."></a>
  <div class="card-body">
    <h5 class="card-title">{{product.name}}</h5>
    <p class="card-text">{{product.price}}</p>

  </div>
</div>
            </div>
     {%endfor%}
        <div class="mx_auto">
            {%if products.paginator.num_pages > 1%}
            <hr>
            <div  class="text-center">
                {%for pg in products.paginator.page_range%}
                <a href="?page={{pg}}" class="btn btn-light btn-sm{%if products.number == pg%}active{%endif%}">{{pg}}</a>
                {%endfor%}
            </div>
            {%endif%}
        </div>

    </div>
    </div>
</div>
{%endblock%}

ecommerceproject/templates/footer.html
<div class="my_footer text-center">
    <p>@copy; Aswathi. All rights Reserved</p>
</div>

ecommerceproject/templates/header.html
{%load static%}
<header style="background-color:black;">
    <center>
        <img src="{%static 'img/logo.png'%}" alt='logo' height="130px">
    </center>
</header>

ecommerceproject/templates/login.html
<!DOCTYPE html>
{% load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
  <!-- Favicons -->
<meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/css/materialize.min.css" rel="stylesheet">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js"></script>
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <link href="{%static 'userRegistration/reg.css'%}" rel="stylesheet">
  <script src="{%static 'userRegistration/reg.js'%}"></script>


  <!-- Template Main CSS File -->


    <title>Title</title>
</head>
<body>
<div class="container">
    <h1>Login</h1>
<div class="row">
    <form class="col s12" id="reg-form" method="post" action="login">
  {% csrf_token %}
      <div class="row">
        <div class="input-field col s12">
          <input id="username" type="text" name="username" placeholder="Username" class="validate" required>
        </div>
      </div>

      <div class="row">
        <div class="input-field col s12">
          <input id="password" type="password" name="password" placeholder="Password" class="validate" minlength="6" required>
        </div>
      </div>

      <div class="row">


        <div class="input-field col s6">
          <button class="btn btn-large btn-register waves-effect waves-light" type="submit" name="action">Login
          </button>
        </div>
          <div class="col s6">

        </div>
      </div>
    </form>

  </div>

  <!--<a title="Login" class="ngl btn-floating btn-large waves-effect waves-light red"><i class="material-icons">input</i></a>-->

</div>




</body>
</html>

ecommerceproject/templates/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

ecommerceproject/templates/nav.html
<nav class="navbar navbar-expand-lg bg-dark">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active text-white" aria-current="page" href="{% url 'shop:allProdCat'%}">Home</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Shop
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{%url 'shop:allProdCat'%}">All Products</a></li>
             {%for cat in links%}
            <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
            {%endfor%}
          </ul>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
           <i class="fa fa-user-circle-o"></i>
          </a>
        {% if user.is_authenticated%}
        <ul class="dropdown-menu">
           <li>{{user_name}}</li>
           <li><a class="dropdown-item" aria-current="page" href="{% url 'credential:logout' %}">Logout</a></li>
        </ul>
<!--         <li class="nav-item">-->
<!--          <a class="nav-link active text-white" aria-current="page" href="{% url 'credential:logout' %}">Logout</a>-->
<!--        </li>-->
        {%else%}
         <ul class="dropdown-menu">
          <li><a class="dropdown-item" aria-current="page" href="{% url 'credential:register' %}">Register</a></li>
          <li>
           <a class="dropdown-item" aria-current="page" href="{% url 'credential:login' %}">Login</a>
          </li>
         </ul>
        {%endif%}
        {%if item_count > 0%}
        <li class="nav-item">
          <a class="nav-link text-white" href="{%url 'cart:cart_detail' %}"><i class="fa fa-shopping-cart">{{item_count}}</i>
          </a>
        </li>
        {%endif%}
      </ul>
      <form class="d-flex dd" role="search" method="get" action="{%url 'search_app:searchResult'%}">
        <input class="form-control me-2" type="search" placeholder="Search" name='q' aria-label="Search">
        <button  type="submit"><i class="fa fa-search "></i></button>
      </form>
    </div>
  </div>
</nav>

ecommerceproject/templates/product.html
{%extends 'base.html'%}
{%load static%}
{%block metadescription%}
{{procduct.description|truncatewords:155}}
{%endblock%}
{%block title%}
{{product.name}}
{%endblock%}
{%block content%}
<div class="container">
<div>
    <div>
        <p>
            <a href="{%url 'shop:allProdCat'%}">Home</a>|<a href="{{product.category.get_url}}">{{product.category}}</a>|{{product.name}}
        </p>
    </div>
</div>
<br>
<div class="row">
    <div class="col-12 col-md-12 col-sm-12 col-lg-6 text-center">
        <div>
            <img src="{{product.image.url}}" style="min-width:18rem;height:18rem;" alt="{{product.name}}">
        </div>
    </div>
    <div class="col-12 col-md-12 col-sm-12 col-lg-6 ">
        <div>
            <h1 class="text-header">{{product.name}}</h1>
            <p class="my_title">${{product.price}}</p>
            <p class="text-justify">{{product.description}}</p>
            {%if product.stock <= 0%}
                <p><b>OutOfStock</b></p>
            {%else%}
                <a class="btn btn-light" href="{%url 'cart:add_cart' product.id%}">Add to Cart</a>
            {%endif%}
        </div>
    </div>
</div>
    </div>
{%endblock%}

ecommerceproject/templates/register.html
<!DOCTYPE html>
{% load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
  <!-- Favicons -->
<meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/css/materialize.min.css" rel="stylesheet">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js"></script>
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <link href="{%static 'userRegistration/reg.css'%}" rel="stylesheet">
  <script src="{%static 'userRegistration/reg.js'%}"></script>


  <!-- Template Main CSS File -->


    <title>Title</title>
</head>
<body>
<div class="container">
    <h4>Registration</h4>
<div class="row">
    <form class="col s12" id="reg-form" method="post" action="register">
  {% csrf_token %}
      <div class="row">
        <div class="input-field col s12">
          <input id="username" type="text" name="username" placeholder="Username" class="validate" required>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s6">
          <input id="first_name" type="text" name="first_name" placeholder="First Name" class="validate" required>
        </div>
        <div class="input-field col s6">
          <input id="last_name" type="text"name="last_name" placeholder="Last Name"class="validate" required>

        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <input id="email" type="email" name="email" placeholder="Email" class="validate" required>

        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <input id="password" type="password" name="password" placeholder="Password" class="validate" minlength="6" required>
        </div>
      </div>
         <div class="row">
        <div class="input-field col s12">
          <input  type="password" name="cpassword" placeholder="Confirm Password" class="validate" minlength="6" required>
        </div>
      </div>
      <div class="row">


        <div class="input-field col s6">
          <button class="btn btn-large btn-register waves-effect waves-light" type="submit" name="action">Register
          </button>
        </div>
          <div class="col s6">
           {%for msg in messages%}
      <p style="color:red;">{{msg}}</p>
     {%endfor%}
        </div>
      </div>
    </form>

  </div>

  <!--<a title="Login" class="ngl btn-floating btn-large waves-effect waves-light red"><i class="material-icons">input</i></a>-->

</div>




</body>
</html>

ecommerceproject/templates/search.html
{%extends 'base.html'%}
{% load static%}
{%block metadescription %}
    We have variety of stunning products
{%endblock%}
{%block title%}
Search
{%endblock%}
{%block content%}
<div>
    <p class="text-center my_search_text">You have searched for  <b>{{query}}</b></p>
</div>

<div class="container">
    <div class="row">
    {%for product in products%}
        <div class="col-md-4 col-9 col-sm-12 col-lg-4 my_bottom_margin">
    <div class="card text-center" style="min-width:18rem;height:25rem;">
        <a href="{{product.get_url}}"><img class="product_img product_img_padding"src="{{product.image.url}}" class="card-img-top" alt="..."></a>
  <div class="card-body">
    <h5 class="card-title">{{product.name}}</h5>
    <p class="card-text">{{product.price}}</p>

  </div>
</div>
            </div>
        {%empty%}
        <div class="row mx-auto">
            <p class="text-center my_search_text">0 result found</p>

        </div>
     {%endfor%}

{%endblock%}